### ISSUE TITLE
How to use inside browser?

### ISSUE THREAD

**Issue by creeperyang** [creeperyang/pinyin#1]
<img width="295" alt="2017-05-12 2 37 33" src="https://cloud.githubusercontent.com/assets/8046480/25986097/a86896c2-3720-11e7-9bfe-17285f8005f0.png">

See <https://creeperyang.github.io/pinyin/>, this is an online demo.

The simplest way is include `<script src="https://creeperyang.github.io/pinyin/browser.js"></script>` and write your business code:

```js
$dom.textContent = Pinyin.convertToPinyin('汉字', null, true）
```

The `browser.js` is umd lib.

---

Of course we can install with npm and use `webpack` to bundle our app.

**Comment by cdll** [comment]
do it support amd or cmd loader?

**Comment by creeperyang** [comment]
@cdll Yes. And you can use with bundle tools too.
