### ISSUE TITLE
在 Chrome 高版本中没有问题，但是 Chromeium 有点小问题

### ISSUE THREAD

**Issue by zhengxiansen** [creeperyang/pinyin#10]
虽然应该没人会用 Chromeium，但是不排除有可能有 浏览器兼容问题，或者其他问题，项目中用还是悠着点吧

Chromeium ： console 截图

![image](https://user-images.githubusercontent.com/7506913/33940182-fc942294-e048-11e7-8d05-81c651604db0.png)

![image](https://user-images.githubusercontent.com/7506913/33940336-874cbd38-e049-11e7-9ef4-50e09e0394c1.png)

readme 中的demo也是这样的，不过 chrome 中一切正常

**Comment by zhengxiansen** [comment]
chromeium
![image](https://user-images.githubusercontent.com/7506913/33940364-9f0330ba-e049-11e7-94b9-a855a82711c3.png)

**Comment by creeperyang** [comment]
应该是ICU的问题。不同的环境有不同的ICU版本，导致不同的排序，所以我们要为其定制一个字典。

通常情况下，我们可能只要更改少数几个位置（相对于主字典）可能就可以拿到常用字正确拼音，但这也可能是个耗时工作（比如我适配IE的过程就因为太耗时中断了）。

目前我没有时间更新字典来使其在 Chromeium 里正常工作，**很抱歉**。如果你有空可以提PR，非常**欢迎👏**。

**Comment by zhengxiansen** [comment]
哈，你太客气了，不过我对这个东西不太熟，可能没办法帮你，不过我很愿意做小白鼠的，对个人项目来说非常好用，Thanks♪(･ω･)ﾉ
