### ISSUE TITLE
小程序android不支持，提示不支持intl，所以只能放弃使用sad

### ISSUE THREAD

**Issue by yuanmouren1hao** [creeperyang/pinyin#17]
![image](https://user-images.githubusercontent.com/5896230/57213164-8be3d100-7018-11e9-8a05-20f74e28ed1b.png)

不知道作者是否有解决的打算

**Comment by yuanmouren1hao** [comment]
看了issue4，看起来作者不打算修复，只能放弃使用了。。

**Comment by yuanmouren1hao** [comment]
推荐使用：https://github.com/sxei/pinyinjs，亲测有用，就是大了一点

**Comment by creeperyang** [comment]
sad 😞
