### ISSUE TITLE
"浮" 显示 fou

### ISSUE THREAD

**Issue by kevinqqnj** [creeperyang/pinyin#2]
谢谢你的项目！
"浮" 显示 fou，应该是 fu

可能还有不少小错误，希望能全面测试一下

**Comment by creeperyang** [comment]
@kevinqqnj 目前仅仅node6/7测试通过，之后会加上浏览器测试。

**Comment by creeperyang** [comment]
今天测试了下浏览器（`Chrome/FireFox/Safari`）:

1. `Chrome/FireFox`通过了测试，即可以得出常用6700+汉字的正确拼音。（非常用汉字不在测试范围内，不保证准确性）。
2. `Safari`无法通过全部测试。

<img width="750" alt="2017-05-20 3 46 08" src="https://cloud.githubusercontent.com/assets/8046480/26274096/8507b1c8-3d73-11e7-8159-264a04dc4eb7.png">

相关讨论： <https://bugs.chromium.org/p/v8/issues/detail?id=459>
