### ISSUE TITLE
Could not install from "tiny-pinyin" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by iugo** [creeperyang/pinyin#6]
2117 verbose Darwin 16.6.0
2118 verbose argv "/Users/user/.nvm/versions/node/v8.1.2/bin/node" "/Users/user/.nvm/versions/node/v8.1.2/bin/npm" "install"
2119 verbose node v8.1.2
2120 verbose npm  v5.3.0
2121 error code ENOLOCAL
2122 error Could not install from "tiny-pinyin" as it does not contain a package.json file.
2123 verbose exit [ 1, true ]

**Comment by creeperyang** [comment]
Any more details? Such as which command used to install `tiny-pinyin`.

**Comment by iugo** [comment]
在原有项目执行 `npm i tiny-pinyin` 时命令行并没有返回错误. 但是 ESLint 和 webpack 均说找不到这个包.

然后我删除了 `package-lock.json` 和 `node_modules` 文件夹. 再执行 `npm i` 时就出现了这个错误.

**Comment by iugo** [comment]
或许是这个原因: https://github.com/iugo/pinyin/commit/7574e2547b5953430f0496afd5a6cc0162539f4f

**Comment by creeperyang** [comment]
@iugo Thanks.
