### ISSUE TITLE
ES5的话怎么使用？

### ISSUE THREAD

**Issue by coderunner-xinxin** [creeperyang/pinyin#8]

**Comment by creeperyang** [comment]
可以使用 babel 把代码转换到 ES5 。

**Comment by coderunner-xinxin** [comment]
是这样的 我在html文件里直接引用的您的js文件 我的js里需要调用您的方法 请问怎么初始化？我刚才可能描述的不清楚
发自网易邮箱大师
在2017年08月03日 17:48，Creeper 写道： 可以使用 babel 把代码转换到 ES5 。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/creeperyang/pinyin","title":"creeperyang/pinyin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/creeperyang/pinyin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@creeperyang in #8: 可以使用 babel 把代码转换到 ES5 。"}],"action":{"name":"View Issue","url":"https://github.com/creeperyang/pinyin/issues/8#issuecomment-319922715"}}}

**Comment by creeperyang** [comment]
你可以看下 https://github.com/creeperyang/pinyin/tree/master/docs/_source 里我怎么写的。

如果直接引入 <>，那么有个全局对象 `Pinyin`，你可以：

```js
if (Pinyin.siSupported()) {
    Pinyin.convert(string)
}
```

**Comment by coderunner-xinxin** [comment]
好咧 谢啦 明天我试试
发自网易邮箱大师
在2017年08月03日 19:36，Creeper 写道： 你可以看下 https://github.com/creeperyang/pinyin/tree/master/docs/_source 里我怎么写的。
如果直接引入 <>，那么有个全局对象 Pinyin，你可以：
if (Pinyin.siSupported()) {
    Pinyin.convert(string)
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/creeperyang/pinyin","title":"creeperyang/pinyin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/creeperyang/pinyin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@creeperyang in #8: 你可以看下 https://github.com/creeperyang/pinyin/tree/master/docs/_source 里我怎么写的。\r\n\r\n如果直接引入 \u003c\u003e，那么有个全局对象 `Pinyin`，你可以：\r\n\r\n```js\r\nif (Pinyin.siSupported()) {\r\n    Pinyin.convert(string)\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/creeperyang/pinyin/issues/8#issuecomment-319944374"}}}

**Comment by coderunner-xinxin** [comment]
刚才用您说的方法试了，确实直接引用js的话会有一个全局对象Pinyin，非常感谢您的解答🌻🌻🌻谢谢啦
发自网易邮箱大师
在2017年08月03日 19:37，coderunner-xuxin 写道： 
好咧 谢啦 明天我试试
发自网易邮箱大师
在2017年08月03日 19:36，Creeper 写道： 你可以看下 https://github.com/creeperyang/pinyin/tree/master/docs/_source 里我怎么写的。
如果直接引入 <>，那么有个全局对象 Pinyin，你可以：
if (Pinyin.siSupported()) {
    Pinyin.convert(string)
}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/creeperyang/pinyin","title":"creeperyang/pinyin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/creeperyang/pinyin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@creeperyang in #8: 你可以看下 https://github.com/creeperyang/pinyin/tree/master/docs/_source 里我怎么写的。\r\n\r\n如果直接引入 \u003c\u003e，那么有个全局对象 `Pinyin`，你可以：\r\n\r\n```js\r\nif (Pinyin.siSupported()) {\r\n    Pinyin.convert(string)\r\n}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/creeperyang/pinyin/issues/8#issuecomment-319944374"}}}
