### ISSUE TITLE
可以脱离node.js，嵌入html中直接使用么？

### ISSUE THREAD

**Issue by blurm** [creeperyang/pinyin#9]
用script标签引用然后直接在页面中使用？

**Comment by creeperyang** [comment]
可以，文档中有例子。

**Comment by blurm** [comment]
抱歉我对nodejs不是很熟，文档中的示例需要 `require('tiny-pinyin')`，require是不是nodejs的关键字？
我在chrome extension环境里识别不了报错了

**Comment by creeperyang** [comment]
<https://creeperyang.github.io/pinyin/browser.js>  可浏览器里直接用。

引入后 `window` 上挂载了 `Pinyin`:

```js
// 首次使用前必须判断 Pinyin.isSupported
if (Pinyin.isSupported()) {
  Pinyin.convertToPinyin('我') // WO
}
```
